environment:
  matrix:
  - JULIAVERSION: "julialang/bin/winnt/x86/0.4/julia-0.4-latest-win32.exe"
    JAVA_HOME: C:\Program Files (x86)\Java\jdk1.7.0\
  - JULIAVERSION: "julialang/bin/winnt/x64/0.4/julia-0.4-latest-win64.exe"
    JAVA_HOME: C:\Program Files\Java\jdk1.7.0\
  - JULIAVERSION: "julianightlies/bin/winnt/x86/julia-latest-win32.exe"
    JAVA_HOME: C:\Program Files (x86)\Java\jdk1.7.0\
  - JULIAVERSION: "julianightlies/bin/winnt/x64/julia-latest-win64.exe"
    JAVA_HOME: C:\Program Files\Java\jdk1.7.0\

matrix:
  allow_failures:
    - JULIAVERSION: "julialang/bin/winnt/x86/0.4/julia-0.4-latest-win32.exe"
    - JULIAVERSION: "julianightlies/bin/winnt/x86/julia-latest-win32.exe"
    
branches:
  only:
    - master
    - /release-.*/

notifications:
  - provider: Email
    on_build_success: false
    on_build_failure: false
    on_build_status_changed: false

install:
# Download most recent Julia Windows binary
  - ps: (new-object net.webclient).DownloadFile(
        $("http://s3.amazonaws.com/"+$env:JULIAVERSION),
        "C:\projects\julia-binary.exe")
# Run installer silently, output to C:\projects\julia
  - C:\projects\julia-binary.exe /S /D=C:\projects\julia

build_script:
# Need to convert from shallow to complete for Pkg.clone to work
  - IF EXIST .git\shallow (git fetch --unshallow)
  - C:\projects\julia\bin\julia -e "versioninfo();
      Pkg.clone(pwd(), \"JavaCall\"); Pkg.build(\"JavaCall\")"

test_script:
  - C:\projects\julia\bin\julia --check-bounds=yes -e "Pkg.test(\"JavaCall\")"
